/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaseRouteImport } from './routes/_base'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as BaseIndexRouteImport } from './routes/_base/index'
import { Route as BaseAuthenticatedRouteImport } from './routes/_base/_authenticated'
import { Route as BaseAuthRouteRouteImport } from './routes/_base/auth/route'
import { Route as AdminAdminRouteRouteImport } from './routes/_admin/admin/route'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as BaseAuthResetPasswordRouteImport } from './routes/_base/auth/reset-password'
import { Route as BaseAuthForgotPasswordRouteImport } from './routes/_base/auth/forgot-password'
import { Route as BaseAuthAccountVerificationRouteImport } from './routes/_base/auth/account-verification'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin/orders'
import { Route as AdminAdminCategoriesRouteImport } from './routes/_admin/admin/categories'
import { Route as AdminAdminBrandsRouteImport } from './routes/_admin/admin/brands'
import { Route as BaseAuthsignupSigninRouteRouteImport } from './routes/_base/auth/(signup-signin)/route'
import { Route as BaseAuthenticatedProfileIndexRouteImport } from './routes/_base/_authenticated/profile/index'
import { Route as BaseAuthenticatedCartIndexRouteImport } from './routes/_base/_authenticated/cart/index'
import { Route as AdminAdminProductsIndexRouteImport } from './routes/_admin/admin/products/index'
import { Route as BaseAuthsignupSigninSignUpRouteImport } from './routes/_base/auth/(signup-signin)/sign-up'
import { Route as BaseAuthsignupSigninSignInRouteImport } from './routes/_base/auth/(signup-signin)/sign-in'
import { Route as AdminAdminProductsSkuRouteImport } from './routes/_admin/admin/products/sku'

const BaseRoute = BaseRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseRoute,
} as any)
const BaseAuthenticatedRoute = BaseAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => BaseRoute,
} as any)
const BaseAuthRouteRoute = BaseAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => BaseRoute,
} as any)
const AdminAdminRouteRoute = AdminAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const BaseAuthResetPasswordRoute = BaseAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => BaseAuthRouteRoute,
} as any)
const BaseAuthForgotPasswordRoute = BaseAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => BaseAuthRouteRoute,
} as any)
const BaseAuthAccountVerificationRoute =
  BaseAuthAccountVerificationRouteImport.update({
    id: '/account-verification',
    path: '/account-verification',
    getParentRoute: () => BaseAuthRouteRoute,
  } as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminCategoriesRoute = AdminAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminBrandsRoute = AdminAdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const BaseAuthsignupSigninRouteRoute =
  BaseAuthsignupSigninRouteRouteImport.update({
    id: '/(signup-signin)',
    getParentRoute: () => BaseAuthRouteRoute,
  } as any)
const BaseAuthenticatedProfileIndexRoute =
  BaseAuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => BaseAuthenticatedRoute,
  } as any)
const BaseAuthenticatedCartIndexRoute =
  BaseAuthenticatedCartIndexRouteImport.update({
    id: '/cart/',
    path: '/cart/',
    getParentRoute: () => BaseAuthenticatedRoute,
  } as any)
const AdminAdminProductsIndexRoute = AdminAdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const BaseAuthsignupSigninSignUpRoute =
  BaseAuthsignupSigninSignUpRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => BaseAuthsignupSigninRouteRoute,
  } as any)
const BaseAuthsignupSigninSignInRoute =
  BaseAuthsignupSigninSignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => BaseAuthsignupSigninRouteRoute,
  } as any)
const AdminAdminProductsSkuRoute = AdminAdminProductsSkuRouteImport.update({
  id: '/products/sku',
  path: '/products/sku',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/auth': typeof BaseAuthsignupSigninRouteRouteWithChildren
  '/': typeof BaseIndexRoute
  '/admin/brands': typeof AdminAdminBrandsRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/auth/account-verification': typeof BaseAuthAccountVerificationRoute
  '/auth/forgot-password': typeof BaseAuthForgotPasswordRoute
  '/auth/reset-password': typeof BaseAuthResetPasswordRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/products/sku': typeof AdminAdminProductsSkuRoute
  '/auth/sign-in': typeof BaseAuthsignupSigninSignInRoute
  '/auth/sign-up': typeof BaseAuthsignupSigninSignUpRoute
  '/admin/products': typeof AdminAdminProductsIndexRoute
  '/cart': typeof BaseAuthenticatedCartIndexRoute
  '/profile': typeof BaseAuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof BaseAuthsignupSigninRouteRouteWithChildren
  '/': typeof BaseIndexRoute
  '/admin/brands': typeof AdminAdminBrandsRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/auth/account-verification': typeof BaseAuthAccountVerificationRoute
  '/auth/forgot-password': typeof BaseAuthForgotPasswordRoute
  '/auth/reset-password': typeof BaseAuthResetPasswordRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/products/sku': typeof AdminAdminProductsSkuRoute
  '/auth/sign-in': typeof BaseAuthsignupSigninSignInRoute
  '/auth/sign-up': typeof BaseAuthsignupSigninSignUpRoute
  '/admin/products': typeof AdminAdminProductsIndexRoute
  '/cart': typeof BaseAuthenticatedCartIndexRoute
  '/profile': typeof BaseAuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_base': typeof BaseRouteWithChildren
  '/_admin/admin': typeof AdminAdminRouteRouteWithChildren
  '/_base/auth': typeof BaseAuthRouteRouteWithChildren
  '/_base/_authenticated': typeof BaseAuthenticatedRouteWithChildren
  '/_base/': typeof BaseIndexRoute
  '/_base/auth/(signup-signin)': typeof BaseAuthsignupSigninRouteRouteWithChildren
  '/_admin/admin/brands': typeof AdminAdminBrandsRoute
  '/_admin/admin/categories': typeof AdminAdminCategoriesRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_base/auth/account-verification': typeof BaseAuthAccountVerificationRoute
  '/_base/auth/forgot-password': typeof BaseAuthForgotPasswordRoute
  '/_base/auth/reset-password': typeof BaseAuthResetPasswordRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/products/sku': typeof AdminAdminProductsSkuRoute
  '/_base/auth/(signup-signin)/sign-in': typeof BaseAuthsignupSigninSignInRoute
  '/_base/auth/(signup-signin)/sign-up': typeof BaseAuthsignupSigninSignUpRoute
  '/_admin/admin/products/': typeof AdminAdminProductsIndexRoute
  '/_base/_authenticated/cart/': typeof BaseAuthenticatedCartIndexRoute
  '/_base/_authenticated/profile/': typeof BaseAuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/auth'
    | '/'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/users'
    | '/auth/account-verification'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/admin/'
    | '/admin/products/sku'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin/products'
    | '/cart'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/admin/brands'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/users'
    | '/auth/account-verification'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/admin'
    | '/admin/products/sku'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin/products'
    | '/cart'
    | '/profile'
  id:
    | '__root__'
    | '/_admin'
    | '/_base'
    | '/_admin/admin'
    | '/_base/auth'
    | '/_base/_authenticated'
    | '/_base/'
    | '/_base/auth/(signup-signin)'
    | '/_admin/admin/brands'
    | '/_admin/admin/categories'
    | '/_admin/admin/orders'
    | '/_admin/admin/users'
    | '/_base/auth/account-verification'
    | '/_base/auth/forgot-password'
    | '/_base/auth/reset-password'
    | '/_admin/admin/'
    | '/_admin/admin/products/sku'
    | '/_base/auth/(signup-signin)/sign-in'
    | '/_base/auth/(signup-signin)/sign-up'
    | '/_admin/admin/products/'
    | '/_base/_authenticated/cart/'
    | '/_base/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  BaseRoute: typeof BaseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base/': {
      id: '/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/_authenticated': {
      id: '/_base/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BaseAuthenticatedRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/auth': {
      id: '/_base/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof BaseAuthRouteRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_base/auth/reset-password': {
      id: '/_base/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof BaseAuthResetPasswordRouteImport
      parentRoute: typeof BaseAuthRouteRoute
    }
    '/_base/auth/forgot-password': {
      id: '/_base/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof BaseAuthForgotPasswordRouteImport
      parentRoute: typeof BaseAuthRouteRoute
    }
    '/_base/auth/account-verification': {
      id: '/_base/auth/account-verification'
      path: '/account-verification'
      fullPath: '/auth/account-verification'
      preLoaderRoute: typeof BaseAuthAccountVerificationRouteImport
      parentRoute: typeof BaseAuthRouteRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/categories': {
      id: '/_admin/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminCategoriesRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/brands': {
      id: '/_admin/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminAdminBrandsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_base/auth/(signup-signin)': {
      id: '/_base/auth/(signup-signin)'
      path: ''
      fullPath: '/auth'
      preLoaderRoute: typeof BaseAuthsignupSigninRouteRouteImport
      parentRoute: typeof BaseAuthRouteRoute
    }
    '/_base/_authenticated/profile/': {
      id: '/_base/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof BaseAuthenticatedProfileIndexRouteImport
      parentRoute: typeof BaseAuthenticatedRoute
    }
    '/_base/_authenticated/cart/': {
      id: '/_base/_authenticated/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof BaseAuthenticatedCartIndexRouteImport
      parentRoute: typeof BaseAuthenticatedRoute
    }
    '/_admin/admin/products/': {
      id: '/_admin/admin/products/'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_base/auth/(signup-signin)/sign-up': {
      id: '/_base/auth/(signup-signin)/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof BaseAuthsignupSigninSignUpRouteImport
      parentRoute: typeof BaseAuthsignupSigninRouteRoute
    }
    '/_base/auth/(signup-signin)/sign-in': {
      id: '/_base/auth/(signup-signin)/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof BaseAuthsignupSigninSignInRouteImport
      parentRoute: typeof BaseAuthsignupSigninRouteRoute
    }
    '/_admin/admin/products/sku': {
      id: '/_admin/admin/products/sku'
      path: '/products/sku'
      fullPath: '/admin/products/sku'
      preLoaderRoute: typeof AdminAdminProductsSkuRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
  }
}

interface AdminAdminRouteRouteChildren {
  AdminAdminBrandsRoute: typeof AdminAdminBrandsRoute
  AdminAdminCategoriesRoute: typeof AdminAdminCategoriesRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminProductsSkuRoute: typeof AdminAdminProductsSkuRoute
  AdminAdminProductsIndexRoute: typeof AdminAdminProductsIndexRoute
}

const AdminAdminRouteRouteChildren: AdminAdminRouteRouteChildren = {
  AdminAdminBrandsRoute: AdminAdminBrandsRoute,
  AdminAdminCategoriesRoute: AdminAdminCategoriesRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminProductsSkuRoute: AdminAdminProductsSkuRoute,
  AdminAdminProductsIndexRoute: AdminAdminProductsIndexRoute,
}

const AdminAdminRouteRouteWithChildren = AdminAdminRouteRoute._addFileChildren(
  AdminAdminRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRouteRoute: typeof AdminAdminRouteRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRouteRoute: AdminAdminRouteRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BaseAuthsignupSigninRouteRouteChildren {
  BaseAuthsignupSigninSignInRoute: typeof BaseAuthsignupSigninSignInRoute
  BaseAuthsignupSigninSignUpRoute: typeof BaseAuthsignupSigninSignUpRoute
}

const BaseAuthsignupSigninRouteRouteChildren: BaseAuthsignupSigninRouteRouteChildren =
  {
    BaseAuthsignupSigninSignInRoute: BaseAuthsignupSigninSignInRoute,
    BaseAuthsignupSigninSignUpRoute: BaseAuthsignupSigninSignUpRoute,
  }

const BaseAuthsignupSigninRouteRouteWithChildren =
  BaseAuthsignupSigninRouteRoute._addFileChildren(
    BaseAuthsignupSigninRouteRouteChildren,
  )

interface BaseAuthRouteRouteChildren {
  BaseAuthsignupSigninRouteRoute: typeof BaseAuthsignupSigninRouteRouteWithChildren
  BaseAuthAccountVerificationRoute: typeof BaseAuthAccountVerificationRoute
  BaseAuthForgotPasswordRoute: typeof BaseAuthForgotPasswordRoute
  BaseAuthResetPasswordRoute: typeof BaseAuthResetPasswordRoute
}

const BaseAuthRouteRouteChildren: BaseAuthRouteRouteChildren = {
  BaseAuthsignupSigninRouteRoute: BaseAuthsignupSigninRouteRouteWithChildren,
  BaseAuthAccountVerificationRoute: BaseAuthAccountVerificationRoute,
  BaseAuthForgotPasswordRoute: BaseAuthForgotPasswordRoute,
  BaseAuthResetPasswordRoute: BaseAuthResetPasswordRoute,
}

const BaseAuthRouteRouteWithChildren = BaseAuthRouteRoute._addFileChildren(
  BaseAuthRouteRouteChildren,
)

interface BaseAuthenticatedRouteChildren {
  BaseAuthenticatedCartIndexRoute: typeof BaseAuthenticatedCartIndexRoute
  BaseAuthenticatedProfileIndexRoute: typeof BaseAuthenticatedProfileIndexRoute
}

const BaseAuthenticatedRouteChildren: BaseAuthenticatedRouteChildren = {
  BaseAuthenticatedCartIndexRoute: BaseAuthenticatedCartIndexRoute,
  BaseAuthenticatedProfileIndexRoute: BaseAuthenticatedProfileIndexRoute,
}

const BaseAuthenticatedRouteWithChildren =
  BaseAuthenticatedRoute._addFileChildren(BaseAuthenticatedRouteChildren)

interface BaseRouteChildren {
  BaseAuthRouteRoute: typeof BaseAuthRouteRouteWithChildren
  BaseAuthenticatedRoute: typeof BaseAuthenticatedRouteWithChildren
  BaseIndexRoute: typeof BaseIndexRoute
}

const BaseRouteChildren: BaseRouteChildren = {
  BaseAuthRouteRoute: BaseAuthRouteRouteWithChildren,
  BaseAuthenticatedRoute: BaseAuthenticatedRouteWithChildren,
  BaseIndexRoute: BaseIndexRoute,
}

const BaseRouteWithChildren = BaseRoute._addFileChildren(BaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  BaseRoute: BaseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
