/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaseRouteImport } from './routes/_base'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as BaseIndexRouteImport } from './routes/_base/index'
import { Route as BaseProfileIndexRouteImport } from './routes/_base/profile/index'
import { Route as BaseCartIndexRouteImport } from './routes/_base/cart/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as BaseAuthResetPasswordRouteImport } from './routes/_base/auth/reset-password'
import { Route as BaseAuthForgotPasswordRouteImport } from './routes/_base/auth/forgot-password'
import { Route as BaseAuthAccountVerificationRouteImport } from './routes/_base/auth/account-verification'
import { Route as BaseAuthsignupSigninRouteRouteImport } from './routes/_base/auth/(signup-signin)/route'
import { Route as BaseAuthsignupSigninSignUpRouteImport } from './routes/_base/auth/(signup-signin)/sign-up'
import { Route as BaseAuthsignupSigninSignInRouteImport } from './routes/_base/auth/(signup-signin)/sign-in'

const BaseRoute = BaseRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseRoute,
} as any)
const BaseProfileIndexRoute = BaseProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => BaseRoute,
} as any)
const BaseCartIndexRoute = BaseCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => BaseRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const BaseAuthResetPasswordRoute = BaseAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => BaseRoute,
} as any)
const BaseAuthForgotPasswordRoute = BaseAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => BaseRoute,
} as any)
const BaseAuthAccountVerificationRoute =
  BaseAuthAccountVerificationRouteImport.update({
    id: '/auth/account-verification',
    path: '/auth/account-verification',
    getParentRoute: () => BaseRoute,
  } as any)
const BaseAuthsignupSigninRouteRoute =
  BaseAuthsignupSigninRouteRouteImport.update({
    id: '/auth/(signup-signin)',
    path: '/auth',
    getParentRoute: () => BaseRoute,
  } as any)
const BaseAuthsignupSigninSignUpRoute =
  BaseAuthsignupSigninSignUpRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => BaseAuthsignupSigninRouteRoute,
  } as any)
const BaseAuthsignupSigninSignInRoute =
  BaseAuthsignupSigninSignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => BaseAuthsignupSigninRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof BaseIndexRoute
  '/auth': typeof BaseAuthsignupSigninRouteRouteWithChildren
  '/auth/account-verification': typeof BaseAuthAccountVerificationRoute
  '/auth/forgot-password': typeof BaseAuthForgotPasswordRoute
  '/auth/reset-password': typeof BaseAuthResetPasswordRoute
  '/admin': typeof AdminAdminIndexRoute
  '/cart': typeof BaseCartIndexRoute
  '/profile': typeof BaseProfileIndexRoute
  '/auth/sign-in': typeof BaseAuthsignupSigninSignInRoute
  '/auth/sign-up': typeof BaseAuthsignupSigninSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof BaseIndexRoute
  '/auth': typeof BaseAuthsignupSigninRouteRouteWithChildren
  '/auth/account-verification': typeof BaseAuthAccountVerificationRoute
  '/auth/forgot-password': typeof BaseAuthForgotPasswordRoute
  '/auth/reset-password': typeof BaseAuthResetPasswordRoute
  '/admin': typeof AdminAdminIndexRoute
  '/cart': typeof BaseCartIndexRoute
  '/profile': typeof BaseProfileIndexRoute
  '/auth/sign-in': typeof BaseAuthsignupSigninSignInRoute
  '/auth/sign-up': typeof BaseAuthsignupSigninSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_base': typeof BaseRouteWithChildren
  '/_base/': typeof BaseIndexRoute
  '/_base/auth/(signup-signin)': typeof BaseAuthsignupSigninRouteRouteWithChildren
  '/_base/auth/account-verification': typeof BaseAuthAccountVerificationRoute
  '/_base/auth/forgot-password': typeof BaseAuthForgotPasswordRoute
  '/_base/auth/reset-password': typeof BaseAuthResetPasswordRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_base/cart/': typeof BaseCartIndexRoute
  '/_base/profile/': typeof BaseProfileIndexRoute
  '/_base/auth/(signup-signin)/sign-in': typeof BaseAuthsignupSigninSignInRoute
  '/_base/auth/(signup-signin)/sign-up': typeof BaseAuthsignupSigninSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/account-verification'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/admin'
    | '/cart'
    | '/profile'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/account-verification'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/admin'
    | '/cart'
    | '/profile'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/_admin'
    | '/_base'
    | '/_base/'
    | '/_base/auth/(signup-signin)'
    | '/_base/auth/account-verification'
    | '/_base/auth/forgot-password'
    | '/_base/auth/reset-password'
    | '/_admin/admin/'
    | '/_base/cart/'
    | '/_base/profile/'
    | '/_base/auth/(signup-signin)/sign-in'
    | '/_base/auth/(signup-signin)/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  BaseRoute: typeof BaseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base/': {
      id: '/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/profile/': {
      id: '/_base/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof BaseProfileIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/cart/': {
      id: '/_base/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof BaseCartIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_base/auth/reset-password': {
      id: '/_base/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof BaseAuthResetPasswordRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/auth/forgot-password': {
      id: '/_base/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof BaseAuthForgotPasswordRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/auth/account-verification': {
      id: '/_base/auth/account-verification'
      path: '/auth/account-verification'
      fullPath: '/auth/account-verification'
      preLoaderRoute: typeof BaseAuthAccountVerificationRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/auth/(signup-signin)': {
      id: '/_base/auth/(signup-signin)'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof BaseAuthsignupSigninRouteRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/auth/(signup-signin)/sign-up': {
      id: '/_base/auth/(signup-signin)/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof BaseAuthsignupSigninSignUpRouteImport
      parentRoute: typeof BaseAuthsignupSigninRouteRoute
    }
    '/_base/auth/(signup-signin)/sign-in': {
      id: '/_base/auth/(signup-signin)/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof BaseAuthsignupSigninSignInRouteImport
      parentRoute: typeof BaseAuthsignupSigninRouteRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BaseAuthsignupSigninRouteRouteChildren {
  BaseAuthsignupSigninSignInRoute: typeof BaseAuthsignupSigninSignInRoute
  BaseAuthsignupSigninSignUpRoute: typeof BaseAuthsignupSigninSignUpRoute
}

const BaseAuthsignupSigninRouteRouteChildren: BaseAuthsignupSigninRouteRouteChildren =
  {
    BaseAuthsignupSigninSignInRoute: BaseAuthsignupSigninSignInRoute,
    BaseAuthsignupSigninSignUpRoute: BaseAuthsignupSigninSignUpRoute,
  }

const BaseAuthsignupSigninRouteRouteWithChildren =
  BaseAuthsignupSigninRouteRoute._addFileChildren(
    BaseAuthsignupSigninRouteRouteChildren,
  )

interface BaseRouteChildren {
  BaseIndexRoute: typeof BaseIndexRoute
  BaseAuthsignupSigninRouteRoute: typeof BaseAuthsignupSigninRouteRouteWithChildren
  BaseAuthAccountVerificationRoute: typeof BaseAuthAccountVerificationRoute
  BaseAuthForgotPasswordRoute: typeof BaseAuthForgotPasswordRoute
  BaseAuthResetPasswordRoute: typeof BaseAuthResetPasswordRoute
  BaseCartIndexRoute: typeof BaseCartIndexRoute
  BaseProfileIndexRoute: typeof BaseProfileIndexRoute
}

const BaseRouteChildren: BaseRouteChildren = {
  BaseIndexRoute: BaseIndexRoute,
  BaseAuthsignupSigninRouteRoute: BaseAuthsignupSigninRouteRouteWithChildren,
  BaseAuthAccountVerificationRoute: BaseAuthAccountVerificationRoute,
  BaseAuthForgotPasswordRoute: BaseAuthForgotPasswordRoute,
  BaseAuthResetPasswordRoute: BaseAuthResetPasswordRoute,
  BaseCartIndexRoute: BaseCartIndexRoute,
  BaseProfileIndexRoute: BaseProfileIndexRoute,
}

const BaseRouteWithChildren = BaseRoute._addFileChildren(BaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  BaseRoute: BaseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
