/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaseRouteImport } from './routes/_base'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as BaseIndexRouteImport } from './routes/_base/index'
import { Route as BaseAuthRouteRouteImport } from './routes/_base/auth/route'
import { Route as BaseProfileIndexRouteImport } from './routes/_base/profile/index'
import { Route as BaseCartIndexRouteImport } from './routes/_base/cart/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as BaseAuthSignUpRouteImport } from './routes/_base/auth/sign-up'
import { Route as BaseAuthSignInRouteImport } from './routes/_base/auth/sign-in'

const BaseRoute = BaseRouteImport.update({
  id: '/_base',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIndexRoute = BaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BaseRoute,
} as any)
const BaseAuthRouteRoute = BaseAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => BaseRoute,
} as any)
const BaseProfileIndexRoute = BaseProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => BaseRoute,
} as any)
const BaseCartIndexRoute = BaseCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => BaseRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const BaseAuthSignUpRoute = BaseAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => BaseAuthRouteRoute,
} as any)
const BaseAuthSignInRoute = BaseAuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => BaseAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof BaseAuthRouteRouteWithChildren
  '/': typeof BaseIndexRoute
  '/auth/sign-in': typeof BaseAuthSignInRoute
  '/auth/sign-up': typeof BaseAuthSignUpRoute
  '/admin': typeof AdminAdminIndexRoute
  '/cart': typeof BaseCartIndexRoute
  '/profile': typeof BaseProfileIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof BaseAuthRouteRouteWithChildren
  '/': typeof BaseIndexRoute
  '/auth/sign-in': typeof BaseAuthSignInRoute
  '/auth/sign-up': typeof BaseAuthSignUpRoute
  '/admin': typeof AdminAdminIndexRoute
  '/cart': typeof BaseCartIndexRoute
  '/profile': typeof BaseProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_base': typeof BaseRouteWithChildren
  '/_base/auth': typeof BaseAuthRouteRouteWithChildren
  '/_base/': typeof BaseIndexRoute
  '/_base/auth/sign-in': typeof BaseAuthSignInRoute
  '/_base/auth/sign-up': typeof BaseAuthSignUpRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_base/cart/': typeof BaseCartIndexRoute
  '/_base/profile/': typeof BaseProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin'
    | '/cart'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/admin'
    | '/cart'
    | '/profile'
  id:
    | '__root__'
    | '/_admin'
    | '/_base'
    | '/_base/auth'
    | '/_base/'
    | '/_base/auth/sign-in'
    | '/_base/auth/sign-up'
    | '/_admin/admin/'
    | '/_base/cart/'
    | '/_base/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  BaseRoute: typeof BaseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_base': {
      id: '/_base'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_base/': {
      id: '/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BaseIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/auth': {
      id: '/_base/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof BaseAuthRouteRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/profile/': {
      id: '/_base/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof BaseProfileIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_base/cart/': {
      id: '/_base/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof BaseCartIndexRouteImport
      parentRoute: typeof BaseRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_base/auth/sign-up': {
      id: '/_base/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof BaseAuthSignUpRouteImport
      parentRoute: typeof BaseAuthRouteRoute
    }
    '/_base/auth/sign-in': {
      id: '/_base/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof BaseAuthSignInRouteImport
      parentRoute: typeof BaseAuthRouteRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BaseAuthRouteRouteChildren {
  BaseAuthSignInRoute: typeof BaseAuthSignInRoute
  BaseAuthSignUpRoute: typeof BaseAuthSignUpRoute
}

const BaseAuthRouteRouteChildren: BaseAuthRouteRouteChildren = {
  BaseAuthSignInRoute: BaseAuthSignInRoute,
  BaseAuthSignUpRoute: BaseAuthSignUpRoute,
}

const BaseAuthRouteRouteWithChildren = BaseAuthRouteRoute._addFileChildren(
  BaseAuthRouteRouteChildren,
)

interface BaseRouteChildren {
  BaseAuthRouteRoute: typeof BaseAuthRouteRouteWithChildren
  BaseIndexRoute: typeof BaseIndexRoute
  BaseCartIndexRoute: typeof BaseCartIndexRoute
  BaseProfileIndexRoute: typeof BaseProfileIndexRoute
}

const BaseRouteChildren: BaseRouteChildren = {
  BaseAuthRouteRoute: BaseAuthRouteRouteWithChildren,
  BaseIndexRoute: BaseIndexRoute,
  BaseCartIndexRoute: BaseCartIndexRoute,
  BaseProfileIndexRoute: BaseProfileIndexRoute,
}

const BaseRouteWithChildren = BaseRoute._addFileChildren(BaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  BaseRoute: BaseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
